### ISSUE TITLE
Class cast exception from Binder to LocationService

### ISSUE THREAD

**Issue by priyankkasera** [android/testing-samples#355] opened 2020-12-10 09:36 UTC
I was trying to adapt your code for testing my foreground service but unexpectedly it is giving ClassCastException. can anyone help me up please.

**Comment by mrk-han** [comment] 2023-08-25 21:35
Hey @priyankkasera , this is a super late message but typically posting more context with your question would help diagnose the problem more easily. Uploading a project or sample with the bare minimum needed to reproduce the issue is recommended.

However, Issues in this repo are usually reserved for errors in the samples, or suggestions for improving the repo.

Please see: http://stackoverflow.com/questions/tagged/android-testing for questions.

I recommend closing this issue.

**Closed** 2023-08-25 21:40 UTC
